Blogs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from Blogs import views

app_name = "blogs"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

apps/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from apps import views


urlpatterns = [
    path('', views.index, name="index"),
    path('about', views.about, name='about'),
    path('create', views.create, name="create"),
    path('edit/<int:id>/', views.edit, name="edit"),
    path('delete/<int:id>/', views.delete),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from Blogs.feeds import LatestPostsFeed
from Blogs.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('', include('apps.urls')),
    path('blog/', include('Blogs.urls', namespace='blogs')),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blogs/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    tags = TaggableManager()
    STATUS_CHOICES = (
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_in_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()  # Менеджер по умолчанию.
    published = PublishedManager()  # Наш новый менеджер.

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:post_detail', args=[self.publish.year,
                                                 self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
        post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
        name = models.CharField(max_length=80)
        email = models.EmailField()
        body = models.TextField()
        created = models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now=True)
        active = models.BooleanField(default=True)

        class Meta:
            ordering = ('created',)

        def __str__(self):
            return 'Comment by {} on {}'.format(self.name, self.post)

Blogs/forms.py
from django import forms

from Blogs.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

Blogs/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.template.response import TemplateResponse
from django.views.generic import ListView
from taggit.models import Tag

from Blogs.forms import EmailPostForm, CommentForm
from Blogs.models import Post, Comment
from django.db.models import Count


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)  # По 3 статьи на каждой странице.
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу.
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц, возвращаем последнюю.
        posts = paginator.page(paginator.num_pages)
    return TemplateResponse(request, 'blogs/list.html', {'posts': posts, 'page': page, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    # Формирование списка похожих статей.
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]
    # Список активных комментариев для этой статьи.
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в базе данных.
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье.
            new_comment.post = post
            # Сохраняем комментарий в базе данных.
            new_comment.save()
    else:
        comment_form = CommentForm()
    return TemplateResponse(request, 'blogs/detail.html',
                            {'post': post, 'comments': comments,
                             'new_comment': new_comment,
                             'comment_form': comment_form,
                             'similar_posts': similar_posts})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blogs/list.html'


def post_share(request, post_id):
    # Получение статьи по идентификатору.
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Форма была отправлена на сохранение.
        form = EmailPostForm(request.POST)
        if form.is_valid():  # Все поля формы прошли валидацию.
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'kovalevskiy2017@outlook.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return TemplateResponse(request, 'blogs/share.html', {'post': post, 'form': form, 'sent': sent})

templates/blogs/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load staticfiles %}
<html>
<head>
 <title>{% block title %}{% endblock %}</title>
 <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
  <script src="{% static "js/bootstrap.min.js" %}"></script>
</head>
<body>
 <div id="content">
 {% block content %}{% endblock %}
 </div>
 <div id="sidebar">
 <h2>My blog</h2>
<p>This is my blog. I've written {% total_posts %} posts so far.</p>

     <h3>Latest posts</h3>
 {% show_latest_posts 3 %}

     <h3>Most commented posts</h3>
{% get_most_commented_posts as most_commented_posts %}
<ul>
 {% for post in most_commented_posts %}
 <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
 {% endfor %}
</ul>
 <p><a href="{% url "post_feed" %}">Subscribe to my RSS feed</a></p>
 </div>
</body>
</html>

templates/blogs/detail.html
{% extends "blogs/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
 <h1>{{ post.title }}</h1>
 <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
 {{ post.body|markdown }}
    <p>
 <a href="{% url "blogs:post_share" post.id %}">Share this post</a>
</p>

     <p class="tags">
 Similar Post:<br>
 {% for similar in similar_posts %}
 <a href="{% url "blogs:post_list"%}">
 {{ similar.title }}
 </a><br>
 {% endfor %}
</p>





    {% with comments.count as total_comments %}
 <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
   {% endwith %}
    {% for comment in comments %}
        <div class="comment">
    <p class="info">
 Comment {{ forloop.counter }} by {{ comment.name }}
 {{ comment.created }}
 </p>
 {{ comment.body|linebreaks }}
 </div>
{% empty %}
 <p>There are no comments yet.</p>
{% endfor %}
    {% if new_comment %}
 <h2>Your comment has been added.</h2>
{% else %}
 <h2>Add a new comment</h2>
 <form action="." method="post">
 {{ comment_form.as_p }}
 {% csrf_token %}
 <p><input type="submit" value="Add comment"></p>
 </form>
{% endif %}
{% endblock %}

templates/blogs/latest_posts.html
<ul>
 {% for post in latest_posts %}
 <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
 {% endfor %}
</ul>

templates/blogs/list.html
{% extends "blogs/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
 <h1>My Blog</h1>
    {% if tag %}
 <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
 {% for post in posts %}
 <h2>
 <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
 <p class="tags">
 Tags:
 {% for tag in post.tags.all %}
 <a href="{% url "blogs:post_list_by_tag" tag.slug %}">
 {{ tag.name }}
 </a>
 {% if not forloop.last %}, {% endif %}
 {% endfor %}
</p>
 </h2>
 <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
 {{ post.body|markdown|truncatewords_html:30 }}
 {% endfor %}
{#    {% include "blogs/pagination.html" with page=posts %}#}
    {% include "blogs/pagination.html" with  page=posts  %}
{% endblock %}

templates/blogs/pagination.html
<div class="pagination">
     <span class="step-links">
         {% if page.has_previous %}
             <a href="?page={{page.previous_page_number}}">Previous</a>
             {% endif %}
                 <span class="current">
                 Page {{ page.number }} of {{ page.paginator.num_pages }}.
                 </span>
             {% if page.has_next %}
             <a href="?page={{ page.next_page_number }}">Next</a>
         {% endif %}
     </span>
</div>

templates/blogs/share.html
{% extends "blogs/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
 {% if sent %}
 <h1>E-mail successfully sent</h1>
 <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
 {% else %}
 <h1>Share "{{ post.title }}" by e-mail</h1>
 <form action="." method="post">
 {{ form.as_p }}
 {% csrf_token %}
 <input type="submit" value="Send e-mail">
 </form>
 {% endif %}
{% endblock %}