apps/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from apps import views


urlpatterns = [
    path('', views.index, name="index"),
    path('about', views.about, name='about'),
    path('create', views.create, name="create"),
    path('edit/<int:id>/', views.edit, name="edit"),
    path('delete/<int:id>/', views.delete),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from Blogs.feeds import LatestPostsFeed
from Blogs.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('', include('apps.urls')),
    path('blog/', include('Blogs.urls', namespace='blogs')),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path

from images import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
]

images/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
    user = models.ForeignKey(User,
                             related_name='images_created', on_delete=models.CASCADE)
    users_like = models.ManyToManyField(User,
                                        related_name='images_liked',
                                        blank=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify
from django import forms

from images.models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {'url': forms.HiddenInput, }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(
            slugify(image.title),
            image_url.rsplit('.', 1)[1].lower())
        # Скачиваем изображение по указанному адресу.
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)
        if commit:
            image.save()
        return image

images/views.py
import redis
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.views.decorators.http import require_POST

from images.forms import ImageCreateForm
from images.models import Image


r = redis.StrictRedis(host=sgitettings.REDIS_HOST,port=settings.REDIS_PORT,db=settings.REDIS_DB)


@login_required
def image_create(request):
    if request.method == 'POST':
        # Форма отправлена.
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # Данные формы валидны.
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            # Добавляем пользователя к созданному объекту.
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Image added successfully')
            # Перенаправляем пользователя на страницу сохраненного изображения.
            return redirect(new_item.get_absolute_url())
    else:
        # Заполняем форму данными из GET-запроса.
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/create.html', {'section': 'images', 'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    return render(request, 'images/detail.html', {'section': 'images', 'image': image})


@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'ok'})

templates/images/create.html
{% extends "account/base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
 <h1>Bookmark an image</h1>
 <img src="{{ request.GET.url }}" class="image-preview">
 <form action="." method="post">
 {{ form.as_p }}
 {% csrf_token %}
 <input type="submit" value="Bookmark it!">
 </form>
{% endblock %}

templates/images/detail.html
{% extends "account/base.html" %}
{% load thumbnail %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
 <h1>{{ image.title }}</h1>
{% thumbnail image.image "300" as im %}
 <a href="{{ image.image.url }}">
 <img src="{{ im.url }}" class="image-detail">
 </a>
{% endthumbnail %}
 {% with total_likes=image.users_like.count users_like=image.users_like.all %}
 <div class="image-info">
 <div>

 <span class="count">
     <span class="total">{{ total_likes }}</span> like{{ total_likes|pluralize }}</span>
     <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like " class="like button">
 {% if request.user not in users_like %}
 Like
 {% else %}
 Unlike
 {% endif %}
 </a>
 </div>
 {{ image.description|linebreaks }}
 </div>
 <div class="image-likes">
 {% for user in image.users_like.all %}
 <div>
 <img src="{{ user.profile.photo.url }}">
 <p>{{ user.first_name }}</p>
 </div>
 {% empty %}
 Этот образ пока никому не нравится.
 {% endfor %}
 </div>
 {% endwith %}



{% endblock %}

    {% block domready %}
        $('a.like').click(function(e){
            e.preventDefault();
            $.post(
                '{% url "images:like" %}',
                {id: $(this).data('id'),action: $(this).data('action')},
            function(data){
                if (data['status'] == 'ok'){
                    var previous_action = $('a.like').data('action');
                    // Изменяем переменную действия.
                    $('a.like').data('action', previous_action == 'like' ?'unlike' : 'like');
                    // Изменяем текст ссылки.
                    $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
                    // Обновляем общее количество лайков.
                    var previous_likes = parseInt($('span.count .total').text());
                    $('span.count .total').text(
                     previous_action == 'like' ? previous_likes + 1 : previous_likes – 1
                    );
                }
                 });
         });
{% endblock %}